site_name: PHPWord
site_url: https://phpoffice.github.io/PHPWord
repo_url: https://github.com/PHPOffice/PHPWord
repo_name: PHPOffice/PHPWord
edit_uri: edit/develop/docs/

## Theme
theme:
  name: material
  palette:
    #primary: indigo
    # Light mode configuration
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode configuration
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.highlight
    - search.suggest
    - content.code.copy

## Plugins
plugins:
  - search

## Config
extra:
  generator: false
markdown_extensions:
  ## Syntax highlighting
  - pymdownx.highlight
  - pymdownx.superfences
  ## Support for emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  ## Support for call-outs
  - admonition
  - pymdownx.details
use_directory_urls: false
